### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by snej** [lyptt/struct#15]
It doesn't seem to be quite as simple as `gem install struct`, at least not for people on a standard macOS 10.12 system.

* `gem install struct` fails with a filesystem permissions error.
* `sudo gem install struct` gets farther, but ends with:
```bash
...
Fetching: ruby_dep-1.5.0.gem (100%)
ERROR:  Error installing struct:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
$  ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
$  which ruby
/usr/bin/ruby
```

I'm guessing the next step is to use Homebrew to install Ruby so I get a newer version than what's in the OS? (And of course a dependency of _that_ is having Homebrew installed, another step for a vanilla system...)

I have to say I'm sort of reluctant to install another Ruby; I worry about versionitis with existing Ruby scripts I've got, and also that the new install won't have whatever gems I've already got in my system Ruby, so it could break stuff.

**Comment by lyptt** [comment]
Hi @snej, currently struct requires at least ruby 2.2.5. Usually when installing gems on macOS, it's best to have a user-local version of ruby, rather than using the system one.

The reason why this is the case, is that the system version of ruby isn't really intended for general day to day use, it's bundled with the system because various system components require it, or at least this is how I understand it from reviewing documentation from similar gems such as Calabash.

When installing ruby gems, I recommend making use of (Ruby Version Manager)[https://rvm.io/], so that you can maintain a local version of ruby that's easy to update. Ruby Version Manager also allows you to switch between a local ruby installation, and the one provided by macOS.

I do understand however that having to use a non-system provided Ruby installation can be inconvenient, so I'll log an issue to investigate how low we can drop the Ruby requirement. This may allow for a successful installation even when using the system Ruby.

Could I ask what version of macOS you're using?

**Comment by lyptt** [comment]
The issue of struct's minimum ruby version is now being tracked in #16, please follow #16 to stay updated on this.

I've updated the readme to clarify the situation with local ruby versions. Thanks for filing this issue!
