### ISSUE TITLE
Swift Scripting

### ISSUE THREAD

**Issue by TofPlay** [lyptt/struct#19]
Interesting tool 🙂
But why do you use Ruby? 😰
In the Apple world we already have an excellent language for this kind of tool: Swift
Swift can also be used to make iOS, macOS applications and on the server too but as well as to make scripts. 

Take a look at these articles/videos: 
* [Scripting in Swift is Pretty Awesome](https://goo.gl/OiQ8xI)
* [A Beginner’s Guide to Scripting in Swift](https://goo.gl/uylJNa)
* [Swift script all the things!](https://goo.gl/lgA3uZ)

Swift scripts can then be easily converted to executables. Then we juste have to copy on our Mac to use it.
With Swift Apple we offer the ability to make powerful tools and extremely simple to install.

**Comment by lyptt** [comment]
Hi @TofPlay, thanks for filing this issue!

The only reason I chose to use Ruby for this tool was because of the excellent library [Xcodeproj](https://github.com/CocoaPods/Xcodeproj), which is the most robust and fully featured library for reading and writing Xcode project files.

Xcodeproj is the only library that supports working with all of the features in an Xcode project, and it's guaranteed to be kept up to date for as long as CocoaPods is around, as CocoaPods also makes use of this library to interact with Xcode projects.

I went with Xcodeproj as it would simplify the maintenance of this tool, as otherwise the majority of the development effort would be spent ensuring that the tool is kept up to date with any schema changes Apple makes.

I do agree that Swift is a great means for building development tools, Carthage is a great example of this, however unfortunately this wasn't a feasible option for this tool.

**Comment by TofPlay** [comment]
@lyptt  [SwifPM](https://github.com/apple/swift-package-manager) is able to generate Xcode project. So you can take a look at [swift-package-manager/Sources/Xcodeproj](https://github.com/apple/swift-package-manager/tree/master/Sources/Xcodeproj)

**Comment by lyptt** [comment]
Hi @TofPlay, we're going with an alternative way to ensure you don't need to install another version of Ruby to use `struct`. You can track this work in #27. Thanks!

**Comment by TofPlay** [comment]
With Swift and SwiftPM you can generate a binary directly. No need to deal with ruby environment. We just have to copy the binary our Mac 🙂

**Comment by lyptt** [comment]
Hi @TofPlay, unfortunately I don't see it as feasible or a particularly good idea to rewrite the application in Swift from the ground up. `struct`'s codebase is becoming well established and stable, and I don't feel particularly good about throwing all of that away.

Ruby's a great language for tooling, and it's proven to have been a great choice so far in `struct`'s development. The issue of having to deal with Ruby will be left entirely to the developers of this tool once #27 is complete, and I'm quite okay with that! 😀

**Comment by TofPlay** [comment]
Personally for my iOS and macOS projects I don't use any tool that is not provided as a binary. In the past I lost a lot of time with tools written in ruby. I'm not a ruby developer and I'm not interested in becoming one. I prefer to spend my time on my projects or learn more about Swift.
I still thought `struct` is a good idea but sorry I will not use it. If you change your mind about Swift tell me 🙂

**Comment by lyptt** [comment]
@TofPlay as described in #27, `struct` will be packaged as a flat binary installed via Homebrew in the future, so this should achieve what you're looking for. Thanks for your feedback!
