### ISSUE TITLE
Deprecate spec 1.0.0

### ISSUE THREAD

**Issue by lyptt** [lyptt/struct#23]
`struct` is a fast-moving tool, with enhancements being released weekly for the spec format. As spec files are semantically versioned, new parser versions are introduced for each format.

Parsers are guaranteed to be backwards-compatible within the same major version, so this task is to explore how we can deprecate older versions of the spec format without obstructing the tool's end users. By deprecating older versions and eventually removing support for these versions, we reduce the maintenance burden on the tool as time goes on.

Proposed migration route as follows:
- Verify version is deprecated via new method `:is_deprecated(version)` in `StructCore::Specparser`. Raise warning if result is true.
- Remove the parser specifically targeting the deprecated version
- Update the parser one version higher than the deprecated version to accept the deprecated version's spec files
- Update unit test suite for the deprecated version to target the updated parser and ensure all tests pass
- A certain period after deprecation, disable the deprecated version from the updated parser, delete the deprecated version's test suite and ensure all tests pass

**Comment by jcampbell05** [comment]
@lyptt generally with Xcake I tried to time breaking the spec with the Xcode releases since that was usually when I needed to update it to support new Xcode functionality changes.

Also most developers expected my tool to break with a new Xcode release so it was a good way of managing expectations.

**Comment by lyptt** [comment]
Yes absolutely, this is one way of achieving this. I think fundamenatally most Xcode updates are likely to smoothly, unless they suddenly restructure something. For example - Xcode 8's code signing updates only added a few additional code signing options for build configurations, so chances are we'd get away with it until they introduce additional Object subclasses that need to be supported by Xcodeproj.

I'd like to advertise a promise of continued support for older spec file formats so we don't leave our end users behind. I think the idea of maintaining backwards compatibility within the same major version is a decent one, as at least then the codebase can continue moving forward.

**Comment by jcampbell05** [comment]
@lyptt Yeah I think that would be ideal so I think we have two core principals:

1. Guaranteed support for Specs within the same major version to not leave older users behind.
2. Major version bumps for specs will ideally be timed for or after major Xcode releases since this is usually when people expect big changes happen and major releases of Xcodeproj are released.

In practice haven't had to change the DSL in Xcake a great deal so this should be enougth :)  

Xcode 8 was announced in June and released in September so potentially this means when Xcode 8.X or 9 is released this year, it will mean deprecating `1.0.0` by June and dropping by September.

**Comment by lyptt** [comment]
Yup, this sounds good to me!
