### ISSUE TITLE
What's the recommended way of connecting unit tests targets with the framework targets?

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#31]
Hi! I'm developing an iOS framework and decided to try Struct for project generation. Everything is good so far, but I didn't get it how to make the Struct create scheme for the framework target that automatically configured properly for unit tests. Out of the ox, after I regenerate project with Struct, the scheme that is being created by Struct does not configure the "Test" scenario properly with the unit tests target, I have to do it manually in order to make the Cmd+U work as expected.

**Comment by lyptt** [comment]
Hi @maximkhatskevich! Turns out struct wasn't doing a couple of things it needs to for unit tests to work properly with frameworks.

I've gone ahead and fixed this up. I intend to get a release of struct out very shortly with all the improvements made so far, so you should see this in a couple of hours.

To get an idea of how you would go about doing this in struct 1.2.0, check out the [example framework project](https://github.com/lyptt/struct/blob/master/examples/iOS_Framework/project.yml).

**Comment by maximkhatskevich** [comment]
Great, thanks! I look forward to the release!

**Comment by maximkhatskevich** [comment]
This seems to be not fixed even in the 1.2.1

**Comment by lyptt** [comment]
@maximkhatskevich Can you try generating the framework example? This should produce a project with a testable framework.

**Comment by maximkhatskevich** [comment]
I confirm, the example framework project has framework scheme configured properly with the unit tests target. I'll try to compare my project.yml with the example one.

**Comment by maximkhatskevich** [comment]
I use a variable for the framework target and connect the unit tests target with the framework target using refernce/variable as well like this:

```Ruby
references:
        - *ProjectTitle
```

Do you think this might be the reason?

**Comment by maximkhatskevich** [comment]
I had 2 entries of "references:" under the same target, this was the issue. It works if I merge them into one statement. Feel free to close this issue!

**Comment by maximkhatskevich** [comment]
Thanks for the help!
