### ISSUE TITLE
Add a Fastlane Plugin

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#38]
In Xcake we have a nice Fastlane plugin alot of users take advantage of, Struct should consider implementing it's own and advertising it on the repo.

Happy to implement.

**Comment by lyptt** [comment]
Hi @jcampbell05, yes this is definitely a good idea! I think we need to bite the bullet and just downgrade everything to support Ruby 2.0.0 first. Adding a Fastlane plugin will most likely involve requiring struct in the plugin class, so there'll be a Ruby incompatibility there until this is achieved.

**Comment by jcampbell05** [comment]
@lyptt cool, do you have any pointers to where I can help downgrade us to 2.0 ?

**Comment by lyptt** [comment]
@jcampbell05 From my investigations, the main sticking point is `listen`, which would need to be downgraded quite significantly. Check #16 for a complete analysis of dependencies that need changing. Anything else is language functionality we're using internally. The things I noticed was:

- Inline `private_class_method` and `private` statements need replacing
- `to_h` isn't available in 2.0.0, so we'd need to construct hashes by hand rather than with `.map`

**Comment by jcampbell05** [comment]
@lyptt I have a implementation of `to_h` I can donate from Xcake since I encountered issues with using it for my `.tmap` implementation.

**Comment by lyptt** [comment]
@jcampbell05 Sounds good!

**Comment by lyptt** [comment]
No Fastlane integration is currently planned, if there's further interest in this please feel free to file a new issue.
