### ISSUE TITLE
Make 'def ...' declarations to work as expected in Specfile to reuse override statements

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#56]
Sample for testing: https://github.com/maximkhatskevich/MKHRequirement/tree/develop

**Comment by maximkhatskevich** [comment]
Sample for testing: https://github.com/maximkhatskevich/MKHRequirement/tree/develop

**Comment by lyptt** [comment]
Hi @maximkhatskevich, thanks for filing this! This is some kind of strange metaprogramming / scope issue. Definitely one to fix!

**Comment by jcampbell05** [comment]
The issues is potentially caused by a safety feature where i`instance_eval` doesn't allow for access of the outside scope.

So the code in the project DSL and configuration DSL are executed in their own sandboxed scope. This means your custom method doesn't exist to the code in the configuration block hence the error.

We are looking into implementing a fix detailed here http://djellemah.com/blog/2013/10/09/instance-eval-with-access-to-outside-scope/
