### ISSUE TITLE
Struct can't handle Clusterfuck...

### ISSUE THREAD

**Issue by jshier** [lyptt/struct#66]
[Clusterfuck](https://github.com/SlaunchaMan/Clusterfuck) is a blank iOS project that includes every possible extension type, as well as a watch app. If nothing else, this could serve as a stress test for your project migration and generation. There are currently a few issues:

1. During initial migration, many warnings are printed:
`Warning: unrecognised project configuration profile 'app-extension'. Ignoring...`
and similar.
2. During migration, the source folders for each target are named `src-<#target_type>` and folders are created on disk. This was unexpected to me. I'd expect it to match folder structure on disk. Also, the contents of the folders are very strange. Some contain the actual original source folder, others include source from other targets. 
3. Generating a project using the migrated `yml` file ultimately fails with the error:
`[Xcodeproj] Consistency issue: build setting SDKROOT has multiple values: {"Debug"=>"watchos", "Release"=>"iphoneos"}`
That's after several of the same warnings seen during initial migration.

This is all based off of the second commit of Clusterfuck, as it may change in the future.

Thanks for the new tool! 🍻

**Comment by lyptt** [comment]
Wow, that's a great resource @jshier! This will be incredibly useful to add to our integration tests. Thanks for the link!

Yes additional platform support is coming as we work to stabilise the tool and add in a full test suite, currently we're limiting it to macOS and iOS at present, which is why you'll get a lot of warnings about unsupported profiles. The folder naming is purely convention based - we generate prefixed folders to avoid any collisions if you for example migrate to the same directory as the source directory, however this can easily be reverted post-migration.

In terms of the contents of the folders, this is based on what files are attached to what targets at the time of migration. Chances are there are files being shared between multiple targets in that project, which is why you may be getting something you didn't expect. When the migration runs, we inspect every file attached to a target, and copy it to the new folder we generate.

Thanks for the detailed issue, this will be incredibly helpful in narrowing down some of the more obscure migration issues you're seeing.

**Comment by SlaunchaMan** [comment]
Glad you like it! I’m in the process of doing some renaming, so you’ll see some churn, but I will eventually have iOS, watchOS, tvOS, and macOS in there, with all of the extension points the platforms offer.

**Comment by lyptt** [comment]
That's awesome! We'll definitely keep an eye on this. Looks like it'll be incredibly useful for us going forward to make sure we don't break anything 🚀

**Comment by jcampbell05** [comment]
Good little benchmark for Apple Tools in general :)

**Comment by SlaunchaMan** [comment]
Added watchOS, tvOS, and macOS. Fair warning: Xcode gets pretty laggy when you have the project file selected.

**Comment by lyptt** [comment]
The following tasks are necessary to add support for all of these targets:
- [ ]  Add tvOS platform support
  - [ ] Add tvOS platform profile
- [ ] Add watchOS platform support
  - [ ] Add watchOS platform profile

**Comment by lyptt** [comment]
Struct is handling this a lot better in 2.0.0, however we still need to add a few more profiles and tvOS support in order to fully handle this 👍

**Comment by SlaunchaMan** [comment]
PSA: The project has been renamed [Turducken](https://github.com/SlaunchaMan/Turducken), so if you’ve cloned it you’ll need to update to the new URL.

**Comment by lyptt** [comment]
I'm gonna go ahead and close this and keep following the strategy of supporting the project types struct's users request specifically, mainly to keep the maintenance overhead down.
